### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by nsk-mironov** [nsk-mironov/smuggler#1]
- [x] Support private vals and vars
- [x] Support lists and maps
- [x] Support nullable properties
- [x] Support multidimensional arrays
